--/ -----------------------------------------------------------------------------------------------
--/ Класс-интерполятор
--/ -----------------------------------------------------------------------------------------------
class "env_factor"

function env_factor:__init(setter)
	self.setter  = setter	   -- function(value)
	self.current = 1.0
	self.target  = 1.0
end

function env_factor:set_target(v)
	self.target = v
end

function env_factor:update(max_step)
	if self.current == self.target then return end

	local diff = self.target - self.current
	if math.abs(diff) <= max_step then
		self.current = self.target
	else
		self.current = self.current + (diff > 0 and max_step or -max_step)
	end
	self.setter(self.current)
end

-- Жёстко выставить и текущее, и целевое
function env_factor:snap(v)
	if v then
		self.target = v
	end
	self.current = self.target
	self.setter(self.target)
end

--/------------------------------------------------------------------
class "weather_effector"
--/------------------------------------------------------------------
function weather_effector:__init()
	self.environment = level.environment()

	self.zones_counter = 0

	self.current_ambient = 1.0
	self.current_fog = 1.0
	
	self.factors = {
		ambient = env_factor(
			function(v)
				level.environment():set_ambient_color_factor(v)
			end
		),
		fog = env_factor(
			function(v)
				level.environment():set_fog_color_factor(v)
			end
		),
	}

	self.transition_duration = 1500
	self:subscribe_on_update()
end

function weather_effector:subscribe_on_update()
	level.add_call(
		function()
			local delta = device().f_time_delta * 1000
			get_weather_effector():update(delta)
			return false  -- not (db.actor and db.actor:alive())
		end,
		function() end
	)
end

function weather_effector:update(delta)
	local max_step = delta / self.transition_duration
	self.factors.ambient:update(max_step)
	self.factors.fog:update(max_step)
end

function weather_effector:on_zone_enter(zone_params)
	self.zones_counter = self.zones_counter + 1
--	log3("Enter zone [%s] [%s|%s]", self.zones_counter, zone_params.ambient_factor, zone_params.fog_factor)

	self.factors.ambient:set_target(zone_params.ambient_factor)
	self.factors.fog:set_target(zone_params.fog_factor)
end

function weather_effector:on_zone_exit()
	self.zones_counter = self.zones_counter - 1
	
	if self.zones_counter <= 0 then
		self.zones_counter = 0
		self.factors.ambient:set_target(1.0)
		self.factors.fog:set_target(1.0)
		self.environment:set_env_ambient("")
	end
end

function weather_effector:reset()
	self.environment:set_env_ambient("")
	self.environment:set_ambient_color_factor(1.0)
	self.environment:set_fog_color_factor(1.0)
end

--/------------------------------------------------------------------
--/ INSTANCE
--/------------------------------------------------------------------
local _weather_effector = nil

function get_weather_effector()
	if not _weather_effector then
		_weather_effector = weather_effector()
	end
	return _weather_effector
end

--/ -----------------------------------------------------------------------------------------------
class "action_change_weather"
--/ -----------------------------------------------------------------------------------------------
function action_change_weather:__init(obj, st)
	self.object = obj
	self.st = st
	self.actor_inside = false
end
--/------------------------------------------------------------------
--/ RESET SCHEME
--/------------------------------------------------------------------
function action_change_weather:reset_scheme()
end
--/------------------------------------------------------------------
--/ UPDATE
--/------------------------------------------------------------------
function action_change_weather:update(delta)
	if not db.actor then return end --/>
	if self.object:inside(db.actor:center()) then
		if not self.actor_inside then
			self.actor_inside = true
			get_weather_effector():on_zone_enter(self.st)
		end
	elseif self.actor_inside then
		self.actor_inside = false
		get_weather_effector():on_zone_exit()
	end
	
	xr_logic.try_switch_to_another_section(self.object, self.st, db.actor)
end
--/ -----------------------------------------------------------------------------------------------
--/ BINDER
--/ -----------------------------------------------------------------------------------------------
function add_to_binder(obj, ini, scheme, section, st)
	local new_action = this.action_change_weather(obj, st)
	xr_logic.subscribe_action_for_events(obj, st, new_action)
end
--/------------------------------------------------------------------
--/ SET SCHEME
--/------------------------------------------------------------------
function set_scheme(obj, ini, scheme, section, gulag_name)
	local st = xr_logic.assign_storage_and_bind(obj, ini, scheme, section)
	st.logic = xr_logic.cfg_get_switch_conditions(ini, section, obj)
	
	st.sound_ambient = utils.cfg_get_string(ini, section, "sound_ambient", obj, false, "", "indoor")
	st.ambient_factor = utils.cfg_get_number(ini, section, "ambient_factor", obj, false, 0.0)
	st.fog_factor = utils.cfg_get_number(ini, section, "fog_factor", obj, false, 0.0)
end
--/ -----------------------------------------------------------------------------------------------

